services:
  backend:
    build: .
    restart: always
    expose:
      - 80
    environment:
      - LOG_LEVEL=warning
      - PGCONNSTRING=${PGCONNSTRING}
    depends_on:
      - db
    networks:
      - traefik-public
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.docker.network=traefik-public
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`api.visitdonorojo.id`)
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=letsencrypt
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    networks:
      - internal
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  traefik-public:
    external: true
  internal:
    external: false
